@echo off
echo Building githookkit for Windows...

echo Running unit tests with coverage...
go test -v -coverprofile=coverage.out ./...

echo Generating coverage report...
go tool cover -html=coverage.out -o coverage.html

echo Building commit-received application...
go build -o bin/commit-received.exe ./cmd/commit-received

echo Build completed successfully!
echo Coverage report available at: coverage.html
echo Executable available at: bin/commit-received.exe 